In [18]:
import pandas as pd

In [20]:
pop = pd.read_csv(r"C:\Users\pybdt\Documents\Kobe_bus_pop.csv")
pop

,field_1,field_2,field_3,field_4,field_5,field_6,field_7,field_8,field_9,layer,path
0,28107_19177,1,28107,135.096772,34.676621,92176569,69,1,22,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
1,28107_19177,1,28107,135.096772,34.676621,92176570,61,2,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
2,28107_19178,16,28107,135.094742,34.676274,92176571,79,2,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
3,28107_19183,16,28107,135.094742,34.676274,92176583,69,1,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
4,28107_19169,2,28107,135.095534,34.675781,92176553,53,1,21,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
...,...,...,...,...,...,...,...,...,...,...,...
143687,28109_65787,2,28109,135.116567,34.700285,92668935,34,2,23,person_28109,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
143688,28109_65787,2,28109,135.116567,34.700285,92668936,3,2,11,person_28109,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
143689,28109_65788,2,28109,135.122328,34.701680,92668937,53,1,21,person_28109,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
143690,28109_65788,2,28109,135.122328,34.701680,92668938,51,2,23,person_28109,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
143691,28109_65788,2,28109,135.122328,34.701680,92668939,6,2,12,person_28109,file:///C:/Data/PseudoPFLOW/agent/28/person_28...

In [22]:
pop2 = pd.read_csv(r"C:\Users\pybdt\Documents\kobe_add_pop.csv")
pop2

,field_1,field_2,field_3,field_4,field_5,field_6,field_7,field_8,field_9
0,28109_617,1,28109,135.133852,34.718174,92514183,78,1,23
1,28109_617,1,28109,135.133852,34.718174,92514184,75,2,23
2,28109_618,16,28109,135.135118,34.715126,92514185,75,2,23
3,28109_619,2,28109,135.134379,34.717413,92514186,41,1,21
4,28109_619,2,28109,135.134379,34.717413,92514187,30,2,23
...,...,...,...,...,...,...,...,...,...
9260,28109_83452,2,28109,135.120354,34.718356,92717389,46,1,21
9261,28109_83452,2,28109,135.120354,34.718356,92717390,49,2,21
9262,28109_83452,2,28109,135.120354,34.718356,92717391,16,2,14
9263,28109_83453,14,28109,135.120137,34.717026,92717392,53,1,21
9264,28109_83453,14,28109,135.120137,34.717026,92717393,83,2,23

In [25]:
pop = pd.concat([pop, pop2], axis=0)
pop

,field_1,field_2,field_3,field_4,field_5,field_6,field_7,field_8,field_9,layer,path
0,28107_19177,1,28107,135.096772,34.676621,92176569,69,1,22,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
1,28107_19177,1,28107,135.096772,34.676621,92176570,61,2,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
2,28107_19178,16,28107,135.094742,34.676274,92176571,79,2,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
3,28107_19183,16,28107,135.094742,34.676274,92176583,69,1,23,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
4,28107_19169,2,28107,135.095534,34.675781,92176553,53,1,21,person_28107,file:///C:/Data/PseudoPFLOW/agent/28/person_28...
...,...,...,...,...,...,...,...,...,...,...,...
9260,28109_83452,2,28109,135.120354,34.718356,92717389,46,1,21,NaN,NaN
9261,28109_83452,2,28109,135.120354,34.718356,92717390,49,2,21,NaN,NaN
9262,28109_83452,2,28109,135.120354,34.718356,92717391,16,2,14,NaN,NaN
9263,28109_83453,14,28109,135.120137,34.717026,92717392,53,1,21,NaN,NaN
9264,28109_83453,14,28109,135.120137,34.717026,92717393,83,2,23,NaN,NaN

In [27]:
import os

In [30]:
data = []

for f in os.listdir(r'C:/Data/PseudoPFLOW/activity_v2/28/'):
    if f.startswith("act"):
        df = pd.read_csv(r'C:/Data/PseudoPFLOW/activity_v2/28/'+f, names=['pid', 'age', 'gender', 'occupation', 'starttime', 'duration', 'act', 'lon', 'lat', 'zipcode'])
        data.append(df)
        
act = pd.concat(data, axis=0)
act

,pid,age,gender,occupation,starttime,duration,act,lon,lat,zipcode
0,91594494,36,1,21,0,31500,1,135.280966,34.707398,28101
1,91594494,36,1,21,31500,21600,500,135.281167,34.705702,28101
2,91594494,36,1,21,53100,33300,1,135.280966,34.707398,28101
3,91594495,45,1,21,0,18900,1,135.259561,34.734964,28101
4,91594495,45,1,21,18900,1800,400,135.248990,34.730916,28101
...,...,...,...,...,...,...,...,...,...,...
39749,97014014,15,1,14,54000,32400,200,134.445882,35.622752,28586
39750,97014018,5,2,11,0,86400,1,134.442913,35.625720,28586
39751,97014030,18,2,16,0,42300,1,134.442734,35.624843,28586
39752,97014037,5,1,11,0,86400,1,134.445096,35.624121,28586
39753,97014060,5,2,11,0,86400,1,134.443251,35.625110,28586

In [31]:
kobe_act = act[act['pid'].isin(pop['field_6'])]
kobe_act

,pid,age,gender,occupation,starttime,duration,act,lon,lat,zipcode
339,91937408,61,1,21,0,35100,1,135.151701,34.682218,28105
340,91937408,61,1,21,35100,6300,200,135.166259,34.669955,28105
341,91937408,61,1,21,41400,14400,500,135.149042,34.657626,28106
342,91937408,61,1,21,55800,30600,1,135.151701,34.682218,28105
343,91937409,33,1,21,0,24300,1,135.151701,34.682218,28105
...,...,...,...,...,...,...,...,...,...,...
373488,92858007,7,2,12,0,27000,1,135.196997,34.702336,28110
373489,92858007,7,2,12,27000,33300,3,135.199438,34.701581,28110
373490,92858007,7,2,12,60300,26100,1,135.196997,34.702336,28110
373578,92858435,12,2,13,0,27900,1,135.193543,34.693904,28110
373579,92858435,12,2,13,27900,58500,3,135.178051,34.690027,28110

In [32]:
kobe_act.to_csv(r'C:/Data/PseudoPFLOW/activity_v2/28/kobe_bus_act_updated.csv', index=False, header=False)